export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <div className="prose prose-lg">
        <h1 className="text-4xl font-serif font-bold mb-6">Terms of Service</h1>

        <p className="text-sm text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
        <p className="text-gray-700 mb-4">
          By accessing and using Elsebrew, you accept and agree to be bound by these Terms of
          Service. If you do not agree to these terms, please do not use this service.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">2. Description of Service</h2>
        <p className="text-gray-700 mb-4">
          Elsebrew is a café discovery tool that helps users find coffee shops in destination
          cities that match the characteristics of their favorite local cafés. The service uses
          Google Maps Platform APIs and AI to generate recommendations.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">3. Validation/Beta Status</h2>
        <p className="text-gray-700 mb-4">
          Elsebrew is currently a validation project. While the search
          results are real and powered by Google Maps data, the service is provided &quot;as is&quot;
          without guarantees of accuracy, completeness, or continued availability.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">4. Use License</h2>
        <p className="text-gray-700 mb-4">
          You may use Elsebrew for personal, non-commercial purposes. You may not:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mb-4">
          <li>Scrape, copy, or reproduce content from this service without permission</li>
          <li>Use automated tools to access the service</li>
          <li>Attempt to reverse-engineer or extract algorithms from this service</li>
          <li>Violate any applicable laws or regulations</li>
        </ul>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">5. Google Maps Content</h2>
        <p className="text-gray-700 mb-4">
          All café data, photos, and maps are provided by Google Maps Platform and are subject
          to Google&apos;s Terms of Service. This service displays required Google attributions and does not claim
          ownership of this content.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">6. AI-Generated Content</h2>
        <p className="text-gray-700 mb-4">
          Match explanations are generated by AI and may occasionally be inaccurate or incomplete.
          They are provided for informational purposes only and should not be relied upon as the
          sole basis for visiting a café.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">7. User Account and Data</h2>
        <p className="text-gray-700 mb-4">
          If you sign in with Google, you are responsible for maintaining the security of your
          account. Your saved cafés and preferences are stored locally in your browser. The service provider is
          not responsible for data loss due to browser clearing or device changes.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">8. Limitation of Liability</h2>
        <p className="text-gray-700 mb-4">
          Elsebrew is provided &quot;as is&quot; without warranties of any kind. The service provider is not liable for:
        </p>
        <ul className="list-disc pl-6 text-gray-700 mb-4">
          <li>Inaccurate café recommendations</li>
          <li>Closed or relocated businesses</li>
          <li>Service interruptions or data loss</li>
          <li>Any damages arising from your use of the service</li>
        </ul>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">9. Third-Party Links</h2>
        <p className="text-gray-700 mb-4">
          This service contains links to third-party websites (Google Maps, Buy Me A Coffee, etc.).
          The service provider is not responsible for the content or practices of these external sites.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">10. Modifications</h2>
        <p className="text-gray-700 mb-4">
          The service provider reserves the right to modify or discontinue the service at any time without notice.
          These Terms of Service may also be updated from time to time.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">11. Termination</h2>
        <p className="text-gray-700 mb-4">
          The service provider may terminate or suspend your access to the service immediately, without prior
          notice, for any reason, including breach of these Terms.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">12. Governing Law</h2>
        <p className="text-gray-700 mb-4">
          These Terms shall be governed by and construed in accordance with applicable laws,
          without regard to conflict of law provisions.
        </p>

        <h2 className="text-2xl font-serif font-semibold mt-8 mb-4">13. Contact</h2>
        <p className="text-gray-700 mb-4">
          For questions about these Terms, contact me at{' '}
          <a href="mailto:brdners@gmail.com" className="text-espresso hover:underline">
            brdners@gmail.com
          </a>
        </p>
      </div>
    </div>
  );
}
